//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Supermarket
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categorii
    {
        public Categorii()
        {
            this.Produses = new HashSet<Produse>();
        }
    
        public int CategorieID { get; set; }
        public string NumeCategorie { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<Produse> Produses { get; set; }
    }
}
