//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Supermarket
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetaliiBon
    {
        public int DetaliuID { get; set; }
        public int BonID { get; set; }
        public int ProdusID { get; set; }
        public int Cantitate { get; set; }
    
        public virtual BonuriCasa BonuriCasa { get; set; }
        public virtual Produse Produse { get; set; }
    }
}
