//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Supermarket
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utilizatori
    {
        public Utilizatori()
        {
            this.BonuriCasas = new HashSet<BonuriCasa>();
        }
    
        public int UtilizatorID { get; set; }
        public string NumeUtilizator { get; set; }
        public string Parola { get; set; }
        public string TipUtilizator { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<BonuriCasa> BonuriCasas { get; set; }
    }
}
