//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Supermarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BonuriCasa
    {
        public BonuriCasa()
        {
            this.DetaliiBons = new HashSet<DetaliiBon>();
        }
    
        public int BonID { get; set; }
        public System.DateTime DataEliberarii { get; set; }
        public int UtilizatorID { get; set; }
    
        public virtual Utilizatori Utilizatori { get; set; }
        public virtual ICollection<DetaliiBon> DetaliiBons { get; set; }
    }
}
